// Generated by tools/build_seed.py. Built-in starter content shared by the public and private builds.
// The app adds these when they are missing (e.g. a cached seed.json from an older version).
export const STARTERS = {
 "exercises": [
  {
   "id": "norwegian-4x4",
   "name": "Norwegian 4x4",
   "fields": [
    "time",
    "flights",
    "rpe",
    "hr",
    "variant"
   ],
   "equip": null,
   "video": null,
   "rehab": null,
   "cues": [
    "Target zone: 85-95% of your max heart rate in each 4 min interval (about RPE 8-9). Warm-up and cool-down are easy, about 60-70%.",
    "Talk test: during an interval you can only get out a few words at a time.",
    "Keep moving in the 3 min recovery: walk or spin easy, don't stop or sit down.",
    "Once or twice a week is enough."
   ],
   "eachSide": false,
   "srcNotes": [],
   "source": "Cardio",
   "rest": null,
   "tempo": null,
   "variants": [
    "Stairs",
    "Run",
    "Bike",
    "Rower",
    "Other"
   ],
   "rangeKg": null,
   "group": "Cardio",
   "starter": {
    "rpe": 8,
    "flights": 15
   },
   "cueLabel": "How it works",
   "tags": [
    "85-95% HRmax",
    "RPE 8-9",
    "1-2× per week"
   ]
  }
 ],
 "routines": [
  {
   "id": "norwegian-4x4",
   "name": "Norwegian 4x4",
   "subtitle": "Cardio intervals · 4 × 4 min",
   "kind": "intervals",
   "source": "Cardio",
   "badge": "4×4",
   "ex": "norwegian-4x4",
   "intervals": {
    "warmupSec": 600,
    "workSec": 240,
    "recoverySec": 180,
    "cooldownSec": 300,
    "count": 4
   },
   "zones": {
    "easy": "60-70% HRmax · easy, you could chat",
    "hard": "85-95% HRmax · RPE 8-9 · only a few words",
    "rec": "Keep moving · 60-70% HRmax"
   },
   "modalities": [
    "Stairs",
    "Run",
    "Bike",
    "Rower",
    "Other"
   ]
  }
 ],
 "groupOrder": [
  "Cardio"
 ]
};
